spring.application.name=DentistClinic
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dentist_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Europe/Kyiv'
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Kyiv
logging.level.org.springframework.security = debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
